//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildedRoseCsharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GildedRoseOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GildedRoseOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuildedRoseCsharp.GildedRoseOutput", typeof(GildedRoseOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMGHAI!
        ///-------- day 0 --------
        ///name, sellIn, quality
        ///Butter, 10, 40
        ///Aged Brie, 25, 10
        ///Sulfuras, Hand of Ragnaros, 25, 40
        ///Backstage passes to a TAFKAL80ETC concert, 15, 40
        ///-------- day 1 --------
        ///name, sellIn, quality
        ///Butter, 9, 39
        ///Aged Brie, 24, 11
        ///Sulfuras, Hand of Ragnaros, 25, 40
        ///Backstage passes to a TAFKAL80ETC concert, 14, 41
        ///-------- day 2 --------
        ///name, sellIn, quality
        ///Butter, 8, 38
        ///Aged Brie, 23, 12
        ///Sulfuras, Hand of Ragnaros, 25, 40
        ///Backstage passes to a TAFKAL80ETC concert, 13, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllItemsOutput {
            get {
                return ResourceManager.GetString("AllItemsOutput", resourceCulture);
            }
        }
    }
}
